task:
  name: Build
  persistent_worker:
    labels:
      os: darwin
      arch: arm64
  build_script: swift build
  sign_script: codesign --sign - --entitlements Sources/tart/tart.entitlements --force .build/debug/tart
  binary_artifacts:
    path: .build/debug/tart