project_name: tart

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    prebuilt:
      path: .build/arm64-apple-macosx/debug/tart 
    hooks:
      post: | 
        gon gon.hcl
        mkdir -p .ci/pkg/
        cp .build/arm64-apple-macosx/debug/tart .ci/pkg/
        pkgbuild --root .ci/pkg --version "${CIRRUS_TAG:-0}" --install-location /usr/local/bin/ --identifier com.github.cirruslabs.tart --sign "Developer ID Installer: Fedor Korotkov (9M2P8L4D89)" Tart.pkg
        xcrun notarytool submit Tart.pkg --keychain-profile "notarytool" --wait
        xcrun stapler staple Tart.pkg

before:
  hooks:
    - .ci/set-version.sh
    - swift build -c debug --product tart

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}"
  - id: regular
    name_template: "{{ .ProjectName }}"

release:
  prerelease: auto
  extra_files:
    - glob: Tart.pkg

brews:
  - name: tart
    ids:
      - regular
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the GitHub repository for more information
    homepage: https://github.com/cirruslabs/tart
    description: Run macOS VMs on Apple Silicon
    skip_upload: auto
    dependencies:
      - "cirruslabs/cli/softnet"
    custom_block: |
      depends_on :macos => :monterey
      
      on_macos do
        unless Hardware::CPU.arm?
          odie "Tart only works on Apple Silicon!"
        end
      end
