# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

project_name: tart
version: 2

before:
  hooks:
    - .ci/set-version.sh
    - swift build --arch arm64 --configuration release --product tart
    - swift build --arch x86_64 --configuration release --product tart

builds:
  - id: tart
    builder: prebuilt
    goamd64: [v1]
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    binary: tart
    prebuilt:
      path: '.build/{{- if eq .Arch "arm64" }}arm64{{- else }}x86_64{{ end }}-apple-macosx/release/tart'

universal_binaries:
  - replace: true

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
        entitlements: ./Resources/tart-{{ if or .IsSnapshot .IsNightly }}dev{{ else }}prod{{ end }}.entitlements
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"

app_bundles:
  - name: tart
    extra_files:
      - src: ./Resources/Info.plist
        dst: Contents/Info.plist
      - src: ./Resources/embedded.provisionprofile
        dst: Contents/embedded.provisionprofile
      - src: ./Resources/AppIcon.png
        dst: Contents/Resources/AppIcon.png

archives:
  - name_template: "{{ .ProjectName }}"
    files:
      - LICENSE

release:
  prerelease: auto

brews:
  - name: tart
    repository:
      owner: cirruslabs
      name: homebrew-cli
    caveats: |
      Tart has been installed. You might want to reduce the default DHCP lease time
      from 86,400 to 600 seconds to avoid DHCP shortage when running lots of VMs daily:

        sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.InternetSharing.default.plist bootpd -dict DHCPLeaseTimeSecs -int 600

      See https://tart.run/faq/#changing-the-default-dhcp-lease-time for more details.
    homepage: https://github.com/cirruslabs/tart
    license: "Fair Source"
    description: Run macOS and Linux VMs on Apple Hardware
    skip_upload: auto
    dependencies:
      - "cirruslabs/cli/softnet"
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script "#{libexec}/tart.app/Contents/MacOS/tart"
      generate_completions_from_executable(libexec/"tart.app/Contents/MacOS/tart", "--generate-completion-script")
    custom_block: |
      depends_on :macos => :ventura
