project_name: tart

before:
  hooks:
    - .ci/set-version.sh
    - swift build -c debug --product tart

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    prebuilt:
      path: .build/arm64-apple-macosx/debug/tart 
    hooks:
      post: 
        - gon gon.hcl

archives:
  - name_template: "{{ .ProjectName }}"
    files:
      - src: Resources/embedded.provisionprofile
        dst: Tart.app/Contents
        strip_parent: true
      - src: ".build/arm64-apple-macosx/debug/tart"
        dst: Tart.app/Contents/MacOS
        strip_parent: true

release:
  prerelease: auto

brews:
  - name: tart
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the GitHub repository for more information
    homepage: https://github.com/cirruslabs/tart
    license: "AGPL-3.0"
    description: Run macOS VMs on Apple Silicon
    skip_upload: auto
    dependencies:
      - "cirruslabs/cli/softnet"
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script "#{libexec}/Tart.app/Contents/MacOS/tart"
    custom_block: |
      depends_on :macos => :monterey
      
      on_macos do
        unless Hardware::CPU.arm?
          odie "Tart only works on Apple Silicon!"
        end
      end
