project_name: tart

before:
  hooks:
    - .ci/set-version.sh
    - swift build -c release --product tart
    - gon gon.hcl
    - mkdir -p tart.app/Contents/MacOS
    - cp .build/arm64-apple-macosx/release/tart tart.app/Contents/MacOS/

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    binary: tart.app/Contents/MacOS/tart
    prebuilt:
      path: tart.app/Contents/MacOS/tart

archives:
  - name_template: "{{ .ProjectName }}"
    files:
      - src: Resources/embedded.provisionprofile
        dst: tart.app/Contents
        strip_parent: true
      - LICENSE

release:
  prerelease: auto

brews:
  - name: tart
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the GitHub repository for more information
    homepage: https://github.com/cirruslabs/tart
    license: "Fair Source"
    description: Run macOS VMs on Apple Silicon
    skip_upload: auto
    dependencies:
      - "cirruslabs/cli/softnet"
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script "#{libexec}/tart.app/Contents/MacOS/tart"
    custom_block: |
      depends_on :macos => :monterey
      
      on_macos do
        unless Hardware::CPU.arm?
          odie "Tart only works on Apple Silicon!"
        end
      end
