project_name: tart

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    prebuilt:
      path: .build/arm64-apple-macosx/debug/tart 
    hooks:
      post: 
        - gon gon.hcl
        - .ci/create-pkg.sh

before:
  hooks:
    - .ci/set-version.sh
    - swift build -c debug --product tart

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}"
  - id: regular
    name_template: "{{ .ProjectName }}"

release:
  prerelease: auto
  extra_files:
    - glob: ./dist/Tart-{{ .Tag }}.pkg

brews:
  - name: tart
    ids:
      - regular
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the GitHub repository for more information
    homepage: https://github.com/cirruslabs/tart
    license: "AGPL-3.0"
    description: Run macOS VMs on Apple Silicon
    skip_upload: auto
    dependencies:
      - "cirruslabs/cli/softnet"
    post_install: |
      ENV["SENTRY_DSN"] = "https://606fab64ced94f0991109ac5467e23da@o4504250314522624.ingest.sentry.io/4504606552424448"
      system "#{bin}/tart report-installation"
      ENV.delete("SENTRY_DSN")
    custom_block: |
      depends_on :macos => :monterey
      
      on_macos do
        unless Hardware::CPU.arm?
          odie "Tart only works on Apple Silicon!"
        end
      end
