project_name: tart

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    prebuilt:
      path: .build/arm64-apple-macosx/debug/tart

archives:
  - name_template: "{{ .ProjectName }}"
    files:
      - src: Resources/embedded.provisionprofile
        dst: Tart.app/Contents
        strip_parent: true
      - src: ".build/arm64-apple-macosx/debug/Tart"
        dst: Tart.app/Contents/MacOS
        strip_parent: true

release:
  prerelease: auto
  extra_files:
    - glob: ./.ci/Tart-{{ .Tag }}.pkg

brews:
  - name: tart
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the GitHub repository for more information
    homepage: https://github.com/cirruslabs/tart
    license: "Fair Source"
    description: Run macOS VMs on Apple Silicon
    skip_upload: auto
    dependencies:
      - "cirruslabs/cli/softnet"
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script "#{libexec}/Tart.app/Contents/MacOS/tart"
    custom_block: |
      depends_on :macos => :monterey
      
      on_macos do
        unless Hardware::CPU.arm?
          odie "Tart only works on Apple Silicon!"
        end
      end
